name: build sphinx documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Step 3: Install Sphinx and dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinxawesome-theme sphinx_design

      # Step 4: Build the documentation
      - name: Build Documentation
        run: |
          sphinx-build -b html docs/source docs/build/html -d docs/build/doctrees

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/build/html